export const SET_QUERY = 'SET_QUERY';
// export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_REQUEST = 'FETCH_REQUEST'
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS'
export const FETCH_REQUEST_FAILURE = 'FETCH_REQUEST_FAILURE'
export const FETCH_SINGLE_MOVIE = 'FETCH_SINGLE_MOVIE'

